# https://starship.rs/config/

[aws]
disabled = true

[directory]
truncation_length = 1
fish_style_pwd_dir_length = 1

[gcloud]
disabled = true

[git_branch]
symbol = "ğŸŒ± "
truncation_length = 6
format = "[on $symbol$branch]($style)"

[git_status]
style = 'white'
conflicted = "âœ–"
ahead = "â†‘${count}"
behind = "â†“${count}"
diverged = "â‡•"
untracked = "â€¦"
stashed = "\\$"
modified = "âœš${count}"
staged = '[â—$count](green)'
renamed = "Â»"
deleted = "âœ˜"
format = '(|[$all_status$ahead_behind]($style)) '

[line_break]
disabled = true

[nodejs]
symbol = "â¬¢ "
format = "[\\($symbol$version\\)](bold green) "

[package]
disabled=true

[python]
format = '[\(${symbol}${pyenv_prefix}${version}(|$virtualenv)\)]($style) '
symbol = "ğŸ"
